name: CICD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
      - name: Build Docker image
        run: docker build -t sainarendra2003/node.js .
      
      - name: Publish image to Docker Hub
        run: docker push sainarendra2003/node.js:latest
        
  deploy:
    needs: build
    runs-on: [self-hosted]
    steps:
      - name: Install Docker (if not already installed)
        run: |
          if ! command -v docker &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y docker.io
          fi
      
      - name: Pull image from Docker Hub
        run: docker pull sainarendra2003/node.js:latest
      
      - name: Delete old container (if exists)
        run: docker rm -f nodejs-container || true
      - name: Run Docker container
        run: 
           docker run -d -p 8080:8080 --name nodejs-container -e MONGO_PASSWORD='${{secrets.MONGO_PASSWORD}}' -e PORT='8080' -e DEV_MODE='development'  -e MONGO_URL='${{secrets.MONGO_URL}}' sainarendra2003/node.js
      
  


